# This workflow is disabled
# name: Test and Coverage
# 
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
# 
# env:
#   CARGO_TERM_COLOR: always
# 
# jobs:
#   test:
#     name: Test and Coverage
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       
#       - name: Install Rust
#         uses: actions-rs/toolchain@v1
#         with:
#           profile: minimal
#           toolchain: stable
#           override: true
#       
#       - name: Cache dependencies
#         uses: actions/cache@v3
#         with:
#           path: |
#             ~/.cargo/registry
#             ~/.cargo/git
#             target
#           key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
#           
#       - name: Run tests
#         run: cargo test
#         
#       - name: Install cargo-tarpaulin
#         run: cargo install cargo-tarpaulin
#         
#       - name: Generate coverage report
#         run: cargo tarpaulin --verbose --workspace --skip-clean --out Xml --output-dir coverage
#         
#       - name: Upload coverage to Codecov
#         uses: codecov/codecov-action@v3
#         with:
#           files: ./coverage/cobertura.xml
#           fail_ci_if_error: false